# Generated by Django 3.1.2 on 2020-10-19 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stopwatchlog',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='stopwatchlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 4, 45, 0, 84718), verbose_name='TimeStamp'),
            preserve_default=False,
        ),
    ]
